### ISSUE TITLE
More Informations

### ISSUE THREAD

**Issue by almaweb** [Ridermansb/vue-gmaps#1]
Hi,
Where to put key form google api ?

Thinks

**Comment by Ridermansb** [comment]
Hi @almaweb ...

Sorry, missing in docs..

``` javascript
Vue.use(VueGmaps, {
  key: '<your api here>'
})
```

**Comment by almaweb** [comment]
Hi,
thank yo but demo is not working...

**Comment by Ridermansb** [comment]
I have noticed too. Thank you. :).. fixed

**Comment by almaweb** [comment]
can you provide some example code, i am  new with vuejs...
some working component...

**Comment by Ridermansb** [comment]
Maybe this can help you.. https://github.com/Ridermansb/vue-gmaps/tree/master/demo
