### ISSUE TITLE
Vue 1.0.x support

### ISSUE THREAD

**Issue by limatheus** [Ridermansb/vue-gmaps#2]
Hi,

Many people still using Vue ^1.0.x, have you plans to support vue him?

**Comment by Ridermansb** [comment]
Hi, sorry @limatheus just 2.0.

I've never tested in 1.0, let me know which errors occur.

**Comment by limatheus** [comment]
Hi @Ridermansb 

No errors occurs, simply did not work.
I made some attempts, but didn't  have time to check better.
Maybe in the weekend I try to check again.
Best regards

**Comment by Ridermansb** [comment]
Close this, too old.
