### ISSUE TITLE
Google Maps API warning: RetiredVersion

### ISSUE THREAD

**Issue by matejicekme** [Ridermansb/vue-gmaps#7]
Hi there,

Is an update of the package possible ? Everything works just fine (thank you for that) but got a warning in debug console : 

Google Maps API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version

Thank you !

**Comment by Ridermansb** [comment]
Hi @matejicekme thanks.

The next version will fix that.

**Comment by matejicekme** [comment]
Hi @Ridermansb,

Thank you :) !

**Comment by matejicekme** [comment]
@Ridermansb 
Not working since last Gmap api update ;)
Google Maps API error: DeletedApiProjectMapError

C ya !

**Comment by Ridermansb** [comment]
Publishing fix right now.

You can also specify the version..

```
Vue.use(VueGmaps, {
  key: 'My_Key',
  version: '3'
})
```

**Comment by Ridermansb** [comment]
Fixed on 7f286a0

**Comment by matejicekme** [comment]
Thx mate !

**Comment by freelancewebdev** [comment]
I'm seeing same error, have set to current version 3.55 in the config - no change.

Versioning docs: https://developers.google.com/maps/documentation/javascript/versions
